project:
  type: website

website: 
  title: "<strong>ISSS608</strong>"
  navbar:
    left:
    - text: "🚀 Hands On"
      menu: 
        - text: "1. Introduction to Visual Analytics"
          href: "Hands-on_exercise/Hands-on_ex1/Hands-on_Ex01.html"
        - text: "2. Beyond ggplot2 Fundamentals"
          href: "Hands-on_exercise/Hands-on_ex2/Hands-on_Ex02.html"
        - text: "3. Interactive Data Visualisation"
          href: "Hands-on_exercise/Hands-on_ex3/Hands-on_Ex03.html"
        - text: "4. Fundamentals of Visual Analytics"
          href: "Hands-on_exercise/Hands-on_ex4/Hands-on_Ex04.html"
        - text: "5. Visualising and Analysing Text Data"
          href: "Hands-on_exercise/Hands-on_ex5/Hands-on_Ex05.html"    
        - text: "6. Modelling, Visualising and Analysing Network Data with R"
          href: "Hands-on_exercise/Hands-on_ex6/Hands-on_Ex06.html"
        - text: "7. Visualising and Analysing Time-Oriented Data"
          href: "Hands-on_exercise/Hands-on_ex7/Hands-on_ex7.html"
        - text: "8. WIP"
          href: "Hands-on_exercise/Hands-on_ex8/Hands-on_ex8.html"
               
    - text: "🤖 In Class"
      menu:
          - text: "In-class Exercise 1"
            href: "In-class_Ex/In-class_Ex01/In-class_Ex01.html"   
          - text: "In-class Exercise 2"
            href: "In-class_Ex/In-class_Ex02/In-class_Ex02.html"
          - text: "In-class Exercise 3"
            href: "In-class_Ex/In-class_Ex03/In-class_Ex03.html"
          - text: "In-class Exercise 4"
            href: "In-class_Ex/In-class_Ex04/In-class_Ex4.html"
          - text: "In-class Exercise 5"
            href: "In-class_Ex/In-class_Ex05/In-class_Ex5.html"
          - text: "In-class Exercise 5B"
            href: "In-class_Ex/In-class_Ex05/In-class_Ex5b.html"
          - text: "In-class Exercise 6"
            href: "In-class_Ex/In-class_Ex06/In-class_Ex_6.html"
          - text: "In-class Exercise 6b"
            href: "In-class_Ex/In-class_Ex06/In-class_Ex6b.html"
          - text: "In-class Exercise 7"
            href: "In-class_Ex/In-class_Ex06/In-class_Ex7.html"           

    - text:  "💻 Take Home"
      menu: 
          - text: "Take-home Exercise 1"
            href: "take-home/take-home_ex1/tkx01.html"
          - text: "Take-home Exercise 2"
            href: "Take-home/Take-home_ex2/Take_home_x02.html"
          - text: "Take-home Exercise 3"
            href: "Take-home/Take-home_ex3/Take_home_x03.html"
    
    - text:  "⚙️ Work in Progress"
      menu: 
          - text: "Group Project"
            href: "Group/Group_project"
       
    
    right:
      - about.qmd
      - href: index.qmd
        text: home
      
format:
  html:
    theme: spacelab
    css: styles.css
    toc: true
    includes: 
      in_header: style.css 

editor: visual


