project:
  type: website

website:
  title: "ISSS608"
  navbar:
    left:
    - text:  "Hands-on"
      menu: 
        - text: "1. Introduction to Visual Analytics"
          href: "Hands-on_exercise/Hands-on_ex1/Hands-on_Ex01.html"
        - text: "2. Beyond ggplot2 Fundamentals"
          href: "Hands-on_exercise/Hands-on_ex2/Hands-on_Ex02.html"
        - text: "3. Programming Interactive Data Visualisation & Animated Statistical Graphics with R"
          href: "Hands-on_exercise/Hands-on_ex3/Hands-on_Ex03.html"
        - text: "4. Visualising Distribution, Statistical Analysis, Uncertainty & Building Funnel Plot with R"
          href: "Hands-on_exercise/Hands-on_ex4/Hands-on_Ex04.html"
          
          
    - text: "In-Class"
      menu:
          - text: "In-class Exercise 1"
            href: "In-class_Ex/In-class_Ex01/In-class_Ex01.html"   
          - text: "In-class Exercise 2"
            href: "In-class_Ex/In-class_Ex02/In-class_Ex02.html"
            
    - text:  "Take-home"
      menu: 
          - text: "Take-home Exercise 1"
            href: "Take-home/Take-home_ex1/Take-home_x01.html"
          - text: "Take-home Exercise 2"
            href: "Take-home/Take-home_ex2/Take-home_x02.html"
    
    - text:  "Project"
      menu: 
          - text: "Group Project"
            href: "Group/Group_project"
       
    
    
    right:
      - about.qmd
      - href: index.qmd
        text: Home
      
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual


